name: Java CI/CD Advanced

on: [push, pull_request]

jobs:
  # 1. Compilation + Tests Unitaires + Jacoco
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: 'maven'
      - name: Build and Run Unit Tests
        run: mvn test
      - name: Upload Coverage Report
        if: always() # Pour avoir le rapport même si un test échoue
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: target/site/jacoco/

  # 2. Analyse de qualité (Checkstyle)
  quality:
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Quality checks (Checkstyle)
        run: mvn checkstyle:check

  # 3. Tests d'Intégration
  integration-tests:
    runs-on: ubuntu-latest
    needs: [quality] # On attend juste que la qualité soit OK
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Run Integration tests
        run: mvn test -Dtest=*IntegrationTest,UserServiceTest

  # 4. Job final : Packaging
  package:
    runs-on: ubuntu-latest
    needs: integration-tests
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Build Final JAR
        run: mvn package -DskipTests
      - name: Store Artifact
        uses: actions/upload-artifact@v4
        with:
          name: order-service-app
          path: target/*.jar